kind: Service
apiVersion: v1
metadata:
  name: mywordpress
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: mywordpress
  ports:
    - protocol: TCP
      name: http
      port: 5050
      targetPort: 5050
    - protocol: TCP
      name: ssh
      port: 24
      targetPort: 22
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: mywordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: mywordpress
    spec:
      containers:
      - name: mywordpress
        image: mywordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
          name: http
        - containerPort: 22
          name: ssh
