kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: test
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
    - protocol: TCP
      name: ssh
      port: 22
      targetPort: 22

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
