apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: test
spec:
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: wordpress
  selector:
    app: wordpress
  type: LoadBalancer

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        ports:
        - containerPort: 5050
          name: wordpress
        imagePullPolicy: Never