apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: myftps
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myftps
    spec:
      containers:
      - name: myftps
        image: myftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21

